# Trino 마이그레이션 설정 예시
# 사용법: trino-migrate run trino-migration.yaml

# ============================================================
# 전역 설정
# ============================================================
parallel_tables: 1 # 동시 테이블 처리 수
parallel_partitions: 1 # 동시 파티션 처리 수
parallel_inserts: 8 # INSERT 병렬 수 (Iceberg는 2 권장)
batch_size: 3000 # INSERT 배치 크기
dry_run: false # true로 설정하면 실제 마이그레이션 없이 확인만

# S3 설정 (환경변수 오버라이드)
# source_bucket: source-data-lake
# target_bucket: target-data-lake

# ============================================================
# 개별 테이블 마이그레이션
# ============================================================
tables:
  # ---------------------------------------------------------
  # 기본 S3 복사 (전체 데이터)
  # ---------------------------------------------------------
  # - catalog: hive           # 카탈로그 (필수)
  #   schema: analytics
  #   table: events
  #   method: s3_copy

  # ---------------------------------------------------------
  # S3 복사 + 파티션 필터
  # 특정 날짜 범위의 파티션만 마이그레이션
  # ---------------------------------------------------------
#   - catalog: hive
#     schema: analytics
#     table: daily_metrics
#     method: s3_copy
#     partition_filter:
#       - "dt >= '2024-01-01'"
#       - "dt <= '2024-12-31'"

#   # ---------------------------------------------------------
#   # INSERT SELECT 방식
#   # WHERE 조건으로 데이터 필터링
#   # ---------------------------------------------------------
#   - catalog: hive
#     schema: analytics
#     table: users
#     method: insert_select
#     where: "created_at >= '2024-01-01'"

#   # ---------------------------------------------------------
#   # 카탈로그/스키마/테이블명 변경
#   # hive.prod.orders -> iceberg.prod_backup.orders_2024
#   # ---------------------------------------------------------
#   - catalog: hive
#     schema: prod
#     table: orders
#     method: s3_copy
#     target_catalog: iceberg
#     target_schema: prod_backup
#     target_table: orders_2024

# # ============================================================
# # 스키마 단위 마이그레이션
# # ============================================================
schemas:
  # ---------------------------------------------------------
  # 스키마 전체 테이블 S3 복사 (일부 제외)
  # ---------------------------------------------------------
  - catalog: iceberg # 소스 카탈로그 (타겟도 동일)
    schema: laplacian_3
    method: s3_copy
    # target_catalog 미지정 시 소스와 동일한 카탈로그 사용
    exclude: # 제외할 테이블


#   # ---------------------------------------------------------
#   # 다른 카탈로그로 마이그레이션 + 파티션 필터
#   # hive.logs.* -> iceberg.logs_archive.*
#   # ---------------------------------------------------------
#   - catalog: hive
#     schema: logs
#     method: s3_copy
#     partition_filter:
#       - "dt >= '2024-06-01'"
#     target_catalog: iceberg
#     target_schema: logs_archive
